const Dungeon = [
    [
        {
            type: 'dungeonWall',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonWall',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonWall',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonWall',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: 'home',
        },
        {
            type: 'dungeonWall',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonWall',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonWall',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonWall',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonWall',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    [
        {
            type: 'dungeonFloorHole',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorPatch',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonTreasure',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    [
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    [
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    [
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    [
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    [
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    [
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    [
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    [
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
];

export default Dungeon;
