import Fred from '../NPC/fred';

const Home = [
    [
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'tree',
            npc: null,
            isAccessible: false,
            pathTo: 'forest',
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: 'forest',
        },
        {
            type: 'tree',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    [
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    [
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    [
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    [
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'pillars',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'pillars',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
    ],
    [
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: Fred,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: false,
            pathTo: 'lair',
        },
    ],
    [
        {
            type: 'librarySign',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'pillars',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'pillars',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
    ],
    [
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: 'library',
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    [
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    [
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonEntrance',
            npc: null,
            isAccessible: true,
            pathTo: 'dungeon',
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
];

export default Home;
