import Fred from '../NPC/fred';
import { Enemy1, Enemy2 } from '../NPC/enemy';

const Home = [
    [
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: Enemy2,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: Enemy1,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'tree',
            npc: null,
            isAccessible: false,
            pathTo: 'forest',
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: 'forest',
        },
        {
            type: 'tree',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    [
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    [
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    [
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    [
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'pillars',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'pillars',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
    ],
    [
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: Fred,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: false,
            pathTo: 'lair',
        },
    ],
    [
        {
            type: 'shopSign',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'pillars',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'pillars',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
    ],
    [
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: 'shop',
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    [
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    [
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'dungeonEntrance',
            npc: null,
            isAccessible: true,
            pathTo: 'dungeon',
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
];

export default Home;
