import Magetician from '../NPC/magetician';

const Lair = [
    // ROW INDEX 0
    [
        {
            type: 'lairWindowInside',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairWallInside',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairWallInside',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairWindowInside',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairWallInside',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairWallInside',
            npc: Magetician,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairWindowInside',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairWallInside',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairWallInside',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairWindowInside',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    // ROW INDEX 1
    [
        {
            type: 'lairFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairDesk',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'lairFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairDesk',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'lairFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairDesk',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'lairFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairDesk',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'lairFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    // ROW INDEX 2
    [
        {
            type: 'lairFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairDesk',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'lairFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairDesk',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'lairFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairDesk',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'lairFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairDesk',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'lairFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    // ROW INDEX 3
    [
        {
            type: 'lairFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairFloorBasic',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    // ROW INDEX 4
    [
        {
            type: 'lairWindowOutside',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'lairWallOutside',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'lairWallOutside',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'lairWindowOutside',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'lairDoor',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairWallOutside',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'lairWindowOutside',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'lairWallOutside',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'lairWallOutside',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'lairWindowOutside',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
    ],
    // ROW INDEX 5
    [
        {
            type: 'lairFloorPath',
            npc: null,
            isAccessible: true,
            pathTo: 'home',
        },
        {
            type: 'lairFloorPath',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairFloorPath',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairFloorPath',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairFloorPath',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairFloorGrass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairFloorGrass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairFloorGrass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairFloorGrass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'lairFloorGrass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    // ROW INDEX 6
    [
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
    ],
    // ROW INDEX 7
    [
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
    ],
    // ROW INDEX 8
    [
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
    ],
    // ROW INDEX 9
    [
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
        {
            type: 'empty',
            npc: null,
            isAccessible: false,
            pathTo: null,
        },
    ],
];

export default Lair;
