const Shop = [
    // ROW INDEX 0
    [
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    // ROW INDEX 1
    [
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    // ROW INDEX 2
    [
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    // ROW INDEX 3
    [
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    // ROW INDEX 4
    [
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    // ROW INDEX 5
    [
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    // ROW INDEX 6
    [
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    // ROW INDEX 7
    [
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: 'home',
        },
    ],
    // ROW INDEX 8
    [
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
    // ROW INDEX 9
    [
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'path',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
        {
            type: 'grass',
            npc: null,
            isAccessible: true,
            pathTo: null,
        },
    ],
];

export default Shop;
